# Generated by Django 3.0.3 on 2020-07-11 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Computer', 'Computer'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics')], default=1, max_length=15),
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.school')),
            ],
        ),
    ]
